# Generated by Django 5.2.4 on 2025-07-15 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects',
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.teacher')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='MyApp.classroom')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
