# Generated by Django 5.2.4 on 2025-07-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_remove_classroom_subjects_classsubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.PositiveSmallIntegerField(default=0)),
                ('writing', models.PositiveSmallIntegerField(default=0)),
                ('assignments', models.PositiveSmallIntegerField(default=0)),
                ('class_activity', models.PositiveSmallIntegerField(default=0)),
                ('sports', models.PositiveSmallIntegerField(default=0)),
                ('complaints', models.PositiveSmallIntegerField(default=0)),
                ('rated_on', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.classsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student')),
            ],
        ),
    ]
