# Generated by Django 5.2.4 on 2025-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_studentsubjectrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectrating',
            name='complaints',
            field=models.TextField(blank=True),
        ),
    ]
