# Generated by Django 5.2.4 on 2025-07-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_studentsubjectrating_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectrating',
            name='rated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
