# Generated by Django 5.2.4 on 2025-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_alter_studentsubjectrating_rated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectrating',
            name='ignored',
            field=models.CharField(blank=True, help_text="Comma-separated list of ignored rating types (e.g. 'sports,reading')", max_length=100),
        ),
    ]
