# Generated by Django 5.2.4 on 2025-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_studentsubjectrating_ignored'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubjectrating',
            name='ignored',
        ),
        migrations.RemoveField(
            model_name='studentsubjectrating',
            name='sports',
        ),
    ]
